Primitives:
  beta: 0.996       # discount factor
  gamma: 0.6        # job finding rate parameter
  kappa: 2.37       # vacancy posting cost
  delta_bar: 0.012  # job destruction rate
  sigma: 0.0        # risk aversion parameter
  # Production function parameters
  alpha: 1.0        # utility function parameter
  A: 1.0            # productivity parameter
  
  # Utility function parameters
  chi: 2.0          # utility function parameter
  b_prob: 0.1       # probability of losing unemployment benefits
  n_W: 100          # number of wage grid points
  n_b: 100          # number of benefit grid points
  W_max: 1.0        # Maximum wage
  W_min: 0.0        # Minimum wage

Simulation:
  N: 6000           # Number of agents
  T: 1100           # Number of periods
  t_burn: 100       # Burn-in period
  seed: 1234        # Random seed
