ModelConfig:
  #? Configuration for the search model
  #> Function definitions and parameters
  ModelFunctions:
    #> Definitions and parameters for the functions used in the model
    MatchingFunction:
      type: "CESMatching"
      params:
        gamma: 0.5
    ProductionFunction:
      ProductivityComponent:
        type: "LinearProductivity" # A(h) = A₀ + A₁ * h
        params:
          A0: 0.0 
          A1: 26.0 
      RemoteEfficiencyComponent:
        type: "LinearFirmLogWorker" # g(ψ, h) = ν * ψ - ψ₀ + ϕ * log(h)
        params:
          nu : 1.0  
          phi: 2.5  
          phi0: 1.42
    UtilityFunction:
      type: "PolySeparable" # U(w, α, h) = (a₀ + a₁ w^η_w) + (c₀ + c₁ * h^η_h) * (1 - α)^χ
      # Note: The utility function in the original model was x = w + c0 * (1 - α)^χ
      params:
        a0: 0.0  
        a1: 1.0  
        eta_w: 1.0
        c0: 16.0 
        c1: 0.0
        eta_h: 1.0  #! 1.0 in my original model
        chi: 1.51 #! χ in my original model
  ModelParameters:
    #> Parameters for the model
    kappa: 1.37     # Vacancy posting cost
    beta: 0.996     # Discount factor
    delta_bar: 0.07 # Baseline job destruction rate
    b: 0.1          # unemployment benefits
  ModelGrids:
    # Parameters for the grids used in the model
    RemoteProductivityGrid:
      n_psi: 101 # Number of ψ grid points
      data_file: "data/results/data_density_3d.csv" # File with the data to construct the grid
      data_column: "PSI" # Column with the data to construct the grid
      weight_column: "JOB_CREATION_BIRTHS" # Column with the weights for the data
    SkillGrid:
      # n_h: 70    # Number of s grid points
      # data_file: "data/results/wfh_estimates.csv" # File with the data to construct the grid
      # data_column: "ESTIMATE_WFH_ABLE" # Column with the data to construct the grid
      # weight_column: "_" # Column with the weights for the data (not present in the data file)
      n_h: 70    # Number of s grid points
      data_file: "data/results/skill_dist.csv" # File with the data to construct the grid
      data_column: "SKILL_INDEX" # Column with the data to construct the grid
      weight_column: "PCT_EMP" # Column with the weights for the data (not present in the data file)
    UtilityGrid:
      n_x: 100   # Number of x grid points
      x_min: 5   # Minimum x
      x_max: 26.0 # Maximum x
